begin;
reset role;
insert into auth.users(id,email) values('00000000-0000-0000-0000-000000000001','message1@example.com'),('00000000-0000-0000-0000-000000000002','message2@example.com');
insert into public.agent_message_transports(provider,account_key,organization_id) values('loopmessage','upmore','org');
select t.as_user('00000000-0000-0000-0000-000000000001');
set role authenticated;
select t.must_fail($$select public.agent_message_begin_link()$$,'transport unavailable','disabled transport cannot enroll users');
reset role;
update public.agent_message_transports set enabled=true;
set role authenticated;
select set_config('test.message_command',public.agent_message_begin_link()->>'command',true);
select t.ok(length(current_setting('test.message_command'))=40,'link code contains a random UUID and an explicit CONNECT command');
select t.must_fail($$select * from public.agent_message_link_codes$$,'permission denied','one-time challenge hashes are not client-readable');
select t.must_fail($$insert into public.agent_message_channels(user_id,provider,account_key,contact) values(auth.uid(),'loopmessage','upmore','+13125550123')$$,'permission denied','client cannot self-verify a phone');
select t.must_fail($$select public.agent_message_ingest('loopmessage','upmore','org','+13125550123','link-1',repeat('a',64),'hello',null)$$,'permission denied','client cannot impersonate a provider');
reset role;
create schema msg;
create function msg.link_hash() returns text language sql as $$select encode(sha256(convert_to(substring(current_setting('test.message_command') from 9),'UTF8')),'hex')$$;
select t.must_fail($$select public.agent_message_ingest('loopmessage','upmore','other','+13125550123','link-1',repeat('a',64),'[Account linked]',msg.link_hash())$$,'transport unavailable','another provider organization cannot redeem a link');
select t.ok(public.agent_message_ingest('loopmessage','upmore','org','+13125550999','unlinked',repeat('f',64),'hello')->>'state'='needs_account_link','unknown sender has no financial identity');
select t.ok((select count(*)=0 from public.agent_message_inbox),'unlinked financial content is not persisted');
select set_config('test.message_inbox',(public.agent_message_ingest('loopmessage','upmore','org','+13125550123','link-1',repeat('a',64),'[Account linked]',msg.link_hash())->>'inbox_id'),true);
select set_config('test.message_channel',(select id::text from public.agent_message_channels where contact='+13125550123'),true);
select t.ok((select user_id='00000000-0000-0000-0000-000000000001' and verified_at is not null from public.agent_message_channels),'verified challenge supplies the account owner');
select t.ok((select text='[Account linked]' and kind='account_link' from public.agent_message_inbox),'verified link kind is separate from conversational content');
select t.ok((public.agent_message_ingest('loopmessage','upmore','org','+13125550123','link-1',repeat('a',64),'[Account linked]',msg.link_hash())->>'duplicate')::boolean,'same provider message retries after challenge redemption');
select t.must_fail($$select public.agent_message_ingest('loopmessage','upmore','org','+13125550123','link-2',repeat('a',64),'[Account linked]',msg.link_hash())$$,'link code unavailable','one-time challenge cannot create another linked event');
select t.must_fail($$select public.agent_message_ingest('loopmessage','upmore','org','+13125550123','link-1',repeat('b',64),'changed')$$,'conflicting message identity','same provider ID with changed text is rejected');
select t.must_fail($$select public.agent_message_ingest('loopmessage','upmore','org','+13125550999','link-1',repeat('a',64),'same')$$,'conflicting message identity','duplicate ID cannot substitute another contact');
select public.agent_message_ingest('loopmessage','upmore','org','+13125550123','next-1',repeat('b',64),'What is due tomorrow?');
select t.ok(public.agent_message_claim((select id from public.agent_message_inbox where provider_message_id='next-1')) is null,'messages are processed in conversation order');
select set_config('test.message_lease',public.agent_message_claim(current_setting('test.message_inbox')::uuid)->>'lease_token',true);
select t.ok(public.agent_message_claim(current_setting('test.message_inbox')::uuid) is null,'concurrent processing cannot claim the same turn twice');
select t.ok(public.agent_message_claim((select id from public.agent_message_inbox where provider_message_id='next-1')) is null,'a later turn waits for the current one');
select t.must_fail($$select public.agent_message_complete(current_setting('test.message_inbox')::uuid,gen_random_uuid(),'["wrong worker"]')$$,'lease unavailable','another worker cannot attach replies');
select t.must_fail($$select public.agent_message_complete(current_setting('test.message_inbox')::uuid,current_setting('test.message_lease')::uuid,'["first",42]')$$,'invalid reply','invalid reply batch rolls back all outbound inserts');
select t.ok((select count(*)=0 from public.agent_message_outbox),'partial invalid completion leaves no sendable output');
select public.agent_message_complete(current_setting('test.message_inbox')::uuid,current_setting('test.message_lease')::uuid,'["Connected. Your account is linked."]');
select t.ok((select state='completed' from public.agent_message_inbox where provider_message_id='link-1'),'reply and completed turn commit atomically');
select t.ok((public.agent_message_complete(current_setting('test.message_inbox')::uuid,current_setting('test.message_lease')::uuid,'["Connected. Your account is linked."]')->>'duplicate')::boolean,'completion retries do not produce duplicate bubbles');
select t.must_fail($$select public.agent_message_complete(current_setting('test.message_inbox')::uuid,current_setting('test.message_lease')::uuid,'["different answer"]')$$,'conflicting replies','completed answer cannot be silently replaced');
select public.agent_message_claim((select id from public.agent_message_inbox where provider_message_id='next-1'));
update public.agent_message_inbox set lease_until=now()-interval '1 second' where provider_message_id='next-1';
select t.ok(public.agent_message_claim((select id from public.agent_message_inbox where provider_message_id='next-1')) is null,'expired brain call is not blindly rerun');
select t.ok((select state='uncertain' from public.agent_message_inbox where provider_message_id='next-1'),'crashed turn remains visible for reconciliation');
select public.agent_message_ingest('loopmessage','upmore','org','+13125550123','next-2',repeat('c',64),'Another question');
select t.ok(public.agent_message_claim((select id from public.agent_message_inbox where provider_message_id='next-2')) is null,'unresolved financial turn blocks later context from overtaking it');
select t.as_user('00000000-0000-0000-0000-000000000002');
set role authenticated;
select t.ok((select count(*)=0 from public.agent_message_channels),'channel reads isolate owners');
select t.ok((select count(*)=0 from public.agent_message_inbox),'conversation reads isolate owners');
select t.ok((select count(*)=0 from public.agent_message_outbox),'outbound drafts isolate owners');
select t.must_fail($$select public.agent_message_revoke(current_setting('test.message_channel')::uuid)$$,'channel unavailable','other user cannot disconnect a verified contact');
select set_config('test.message_command',public.agent_message_begin_link()->>'command',true);
reset role;
select t.must_fail($$select public.agent_message_ingest('loopmessage','upmore','org','+13125550123','takeover',repeat('d',64),'[Account linked]',msg.link_hash())$$,'belongs to another account','valid code cannot take over another user contact');
select public.agent_message_ingest('loopmessage','upmore','org','+13125550456','owner-2',repeat('e',64),'[Account linked]',msg.link_hash());
select t.ok((select user_id='00000000-0000-0000-0000-000000000002' from public.agent_message_channels where contact='+13125550456'),'rejected takeover leaves code available for the correct contact');
select t.as_user('00000000-0000-0000-0000-000000000001');
set role authenticated;
select public.agent_message_revoke(current_setting('test.message_channel')::uuid);
reset role;
select t.ok((select state='cancelled' from public.agent_message_inbox where provider_message_id='next-2'),'disconnect cancels queued work');
select t.ok((select state='cancelled' from public.agent_message_outbox),'disconnect cancels unsent replies');
select t.ok(public.agent_message_ingest('loopmessage','upmore','org','+13125550123','revoked-1',repeat('f',64),'new message')->>'state'='needs_account_link','revoked sender cannot reach the financial brain');
select t.ok((select count(*)=4 from public.agent_message_inbox),'disconnect retains conversation history');
rollback;
