#!/usr/bin/env python3
"""Build pure financial domain exports without restoring the retired frontend."""
from pathlib import Path
import argparse

root = Path(__file__).resolve().parents[1]
names = ["33-agent-monitors.js", "35-agent-intents.js", "36-agent-workflows.js",
         "37-agent-financial-model.js", "38-agent-biller-model.js", "39-agent-posted-flow.js", "40-agent-classified-ledger.js", "41-agent-recovery.js"]
exports = ["AgentMonitors", "AgentIntents", "AgentWorkflows", "AgentFinancialModel",
           "AgentBillerModel", "AgentPostedFlow", "AgentClassifiedLedger", "AgentRecovery"]
content = "// Generated by scripts/build-financial-core.py; edit packages/domain instead.\n"
content += "\n".join((root / "packages/domain" / name).read_text() for name in names)
content += "\nexport { " + ", ".join(exports) + " };\n"
parser = argparse.ArgumentParser()
parser.add_argument("--check", action="store_true")
args = parser.parse_args()
for relative in ["supabase/functions/_shared/agent_core.js",
                 "supabase/functions/agent-chat/agent_core.js",
                 "supabase/functions/agent-workflows/agent_core.js"]:
    target = root / relative
    if args.check:
        if not target.exists() or target.read_text() != content:
            raise SystemExit("Financial domain bundle is stale: " + relative)
    else:
        target.write_text(content)
print("Financial domain bundles verified" if args.check else "Financial domain bundles built")
