export const SYSTEM_PROMPT = '';
export const renderRouteCards = (...a: any[]) => null;
export const checkGrounding = (...a: any[]) => null;
export const isDebunkReply = (...a: any[]) => null;
export const findFalseNoRouteClaim = (...a: any[]) => null;
export const appendSources = (...a: any[]) => null;
export const SAFE_FALLBACK = '';
export const FINANCE_SAFE_FALLBACK = '';
export const SCAM_FALLBACK = '';
export type RouteCard = any;
